# ===========================================================================
# ╔╗─╔╗─────╔╗─╔═══╗────╔╗╔═══╗───────╔╗
# ║║─║║─────║║─║╔═╗║────║║║╔══╝───────║║
# ║╚═╝╠══╦══╣║─║║─║╠═╗╔═╝║║╚══╦══╦══╦═╝║
# ║╔═╗║║═╣╔╗║║─║╚═╝║╔╗╣╔╗║║╔══╣║═╣║═╣╔╗║
# ║║─║║║═╣╔╗║╚╗║╔═╗║║║║╚╝║║║──║║═╣║═╣╚╝║
# ╚╝─╚╩══╩╝╚╩═╝╚╝─╚╩╝╚╩══╝╚╝──╚══╩══╩══╝
# ===========================================================================
# Report Plugin: https://github.com/Kylan1940/HealAndFeed/issues/new
# ===========================================================================
# Become a Patron: https://patreon.com/Kylan1940
# Github: https://github.com/Kylan1940
# Website: https://web.kylan1940.online
# Discord Community: discord.io/kylancommunity
# ===========================================================================

# HEAL AND FEED CONFIGURATION
#
# HELP:
# \n for new line
# § for color and special symbols
# {playerGive} for player who given 
# {playerName} for player who give
# {countOnline} for count online player(s)

# Config Version
# DON'T CHANGE THIS!!! 
config-version: 7

# Prefix:
prefix: "§7[§9HealAndFeed§7] "

# Use Permission/Money/Both
# permission = use permission, no BedrockEconomy required, see the wiki for all permissions: https://github.com/Kylan1940/HealAndFeed/wiki/HealAndFeed-Commands
# money = use money, BedrockEconomy required
# NOTE: for HealAndFeed UI, you must to add HealAndFeed UI permission
use: "permission" # (permission/money)

# Command:
no-permission: # Only work if you choose "permission", except for ui
  heal:
    self: "§cYou don't have §aHeal Command §cpermission"
    other: "§cYou don't have §aHeal Other Player Command §cpermission"
    all: "§cYou don't have §aHeal All Command §cpermission"
  feed:
    self: "§cYou don't have §aFeed Command §cpermission"
    other: "§cYou don't have §aFeed Other Player Command §cpermission"
    all: "§cYou don't have §aFeed All Command §cpermission"
  ui:  "§cYou don't have §aHealAndFeed UI Command §cpermission"
console-command:
  heal: "§c/heal is heal for playerself and only in-game, for console you must /heal (playerOnline)"
  feed: "§c/feed is feed for playerself and only in-game, for console you must /feed (playerOnline)"
  ui: "§c/healfeed is only in-game"
no-enough-money: # Only work if you choose "money"
  heal: ""
  feed: ""

# Message:
message:
  receive:
    heal:
      self: "§aYou've been healed"
      other: "§aYou've been healed by {playerName}"
    feed:
      self: "§aYou're full"
      other: "§aYou're full by {playerName}"
  sent:
    heal:
      other: "§aHeal {playerGive} successfully"
      all: "§aHeal all {countOnline} players ({playerGive}) successfully"
    feed:
      other: "§aFeed {playerGive} successfully"
      all: "§aFeed all {countOnline} players ({playerGive}) successfully"
no-player:
  found: "§cThis player does not exist"
  online: "§cThere are no online players in server"

# UI
ui:
  title: "§aHeal§7And§cFeed"
  button: 
    heal: "§aHeal"
    feed: "§cFeed"
    image:
      # (OPTIONAL) if you don't want add a image, you can blank it or write ""
      # See information how to use the image: https://direct.kylan1940.site/other/how-to-use-image-pmmp-plugin
      heal: "textures/ui/heart"
      feed: "textures/ui/hungry_full"

# Money
# It will work if you choose "money"
# BedrockEconomy REQUIRED
money:
  heal: "200"
  feed: "300"